### ISSUE TITLE
[QUESTION] Is It possible to display Panel From top like a navigation view controller?

### ISSUE THREAD

**Issue by ugenlik** [scenee/FloatingPanel#108]
Is something like this possible with `FloatingPanel` library?

Instead of panel starting on the bottom of the screen, it would be on top and would silde down with a pull gesture.

https://blog.mint.com/updates/mint-fresh-new-look-on-ios/

**Comment by SCENEE** [comment]
Now it's not possible, but I'd like to make it to improve the layout and gesture handling.

**Comment by markmosleh** [comment]
hello any updates on the above?

**Comment by jiggaman0412** [comment]
any progress?
I really need this to be done my work.

**Comment by SCENEE** [comment]
Thank you for your patient. I'm going forward to implement this feature step by step because I have to do that without any existing feature breaks. so I've created PR #234  as a big milestone on the roadmap. As the next step, I'm planning to improve the height management. After the feature, at last, I will implement this.

**Comment by scenee** [comment]
It's been supported  since 2.x. Thanks.
