### ISSUE TITLE
Feature Suggestion: Apple Music FloatingPanelBehavior

### ISSUE THREAD

**Issue by mergesort** [SCENEE/FloatingPanel#115]
I was wondering if you'd considered a `FloatingPanelBehavior` that provides some friction before dismissal, and then dismisses before reaching the bottom, similar to the effect you get when using Apple Music.

If not as a feature in the core library, I would appreciate if you had insight into what would be the best way to build a similar mechanism.

Thanks a lot!

**Comment by SCENEE** [comment]
Sounds great! I didn't consider the feature but I agree that it has the possibility.

I think it's the feature can be provided by improve `FloatingPanelLayout` rather than `FloatingPanelBehavior`.

In relation to this, I'm considering how to achieve #108 layout and Apple Maps' floating panel on iPad by an improvement of the layout and gesture handling.

I'd like this library to support more flexible layout configuration when it reaches v2.0.

**Comment by SCENEE** [comment]
I really appreciate your proposal, but I decide not to support this feature by this library because a sheet modal presentation is added on iOS 13 and then a library consumer could be confused about the usage.

**Comment by mergesort** [comment]
I respect that decision, especially with iOS 13's changes! Thanks for the thoughtful response.
