### ISSUE TITLE
[Question] Is it possible to add a floating panel to a navigation controller?

### ISSUE THREAD

**Issue by achan** [SCENEE/FloatingPanel#161]
When trying to add my floating panel to a navigation controller, I'm met with a `precondition` error:

```swift
precondition((parent is UINavigationController) == false, "UINavigationController displays only one child view controller at a time.")
```

I suppose that's my answer right there, but I'd just like confirmation. I want my floating panel to be accessible between all screens, similar to Apple Music's Now Playing panel. Is that unsupported?

I'm aware of the readme:
> FloatingPanelController has no way to manage a stack of view controllers like UINavigationController. 

But I'm not looking for the floating panel to manage the stack, but to be displayed above the navigation controller.

Thanks for your work!

**Comment by SCENEE** [comment]
This is because "A navigation controller is a container view controller that manages one or more child view controllers in a navigation interface." ( Ref . https://developer.apple.com/documentation/uikit/uinavigationcontroller) :relieved:

To support your use case, you can present a floating panel as a modality 👍  https://github.com/SCENEE/FloatingPanel#present-a-floating-panel-as-a-modality

**Comment by achan** [comment]
Perfect. Thank you! 👍
