### ISSUE TITLE
Problem with closing panel during internal scroll view bounce

### ISSUE THREAD

**Issue by Heltisace** [SCENEE/FloatingPanel#218]
### Short description
When closing the panel, if scroll view is still in the process of bouncing, there will be a visual bug. At least for me, it's quite usual to make a quick scroll to the top, which causes bounce, and then try to close the panel.

### Expected behavior
Smooth transition.

### Actual behavior
Glitching. See the video.
[video.mov.zip](https://github.com/SCENEE/FloatingPanel/files/3258725/video.mov.zip)

### Steps to reproduce
Call the top vertical bounce of scroll view and try to close panel at the moment. 

**Code example that reproduces the issue**
[TestingNewPullUp.zip](https://github.com/SCENEE/FloatingPanel/files/3258729/TestingNewPullUp.zip)

**Library version**
1.6.0

**Installation method**
CocoaPods

**iOS version(s)**
12.2

**Xcode version**
10.2.1

**Comment by SCENEE** [comment]
Thanks, @Heltisace! At first, I'm grateful for your video and sample project for this issue because they're much helpful and save my time. Now I've confirmed this issue using them. I will fix this issue later.

**Comment by SCENEE** [comment]
This issue is resolved in the master branch. It will be released on v1.6.x or 1.7.0. Thank you.

**Comment by SCENEE** [comment]
I have 2 notices to you about TestingNewPullUp sample.

1. I found not calling `ChildFloatingPanelController.supportedPositions` expectedly by the Swift issue [SR-103](https://bugs.swift.org/browse/SR-103). You need to add `AnyFloatingPanelController.supportedPositions` and override it in `ChildFloatingPanelController`.

2. I guess `.hidden` support position is not working well as you expected on iPhone X series. The issue is mentioned in https://github.com/SCENEE/FloatingPanel/issues/175.  I'm working now to fix it.

**Comment by Heltisace** [comment]
Ok, thanks. Glad I could help :)
