### ISSUE TITLE
Adds an extra view controller when FloatingPanel is added to a UITabbarViewController

### ISSUE THREAD

**Issue by wsimf** [SCENEE/FloatingPanel#23]
A black view controller is added when the FloatingPanel is added to the `UITabbarViewController`.
I think this happens because the panel is setting itself as a child in `addPanel(toParent:)` method

<img width="270" alt="screen shot 2018-11-01 at 12 27 56 pm" src="https://user-images.githubusercontent.com/1941924/47824481-ff8af400-ddd1-11e8-8a64-ab5f1897048d.png">

**Comment by wsimf** [comment]
Just figured out that one way to overcome this issue is to call `setViewControllers(_:animated:)` on the `UITabbarViewController` after calling `addPanel(toParent:)` on `FloatingPanelController`. I think it just overrides current child view controllers. However, I am not sure of any side-effects due to this.

**Comment by SCENEE** [comment]
UITabBarController displays child view controllers with a radio-style selection interface. So FloatingPanelController doesn't work well when it's added into UITabBarViewController directly because FloatingPanelController is a chid view controller of a parent.

It's out of control from this library. Please add it to a child view controller(a tab) of UITabBarViewController or wrap UITabBarViewController with a view controller.
