### ISSUE TITLE
SearchBar Cancel tap causes panel to dismiss

### ISSUE THREAD

**Issue by swiftymf** [SCENEE/FloatingPanel#248]
I have a searchBar in the tableHeaderView. Panel moves to .full when textField becomes active. If I tap the Cancel button the panel slides completely off the screen. As far as I can tell my code is almost identical to the Maps Sample project with similar functionality. I've checked delegates, positions when cancel is pressed, etc. If I change the position from .full to .half in searchBarTextDidBeginEditing it will change when I run the project. However when I make any change to searchBarCancelButtonClicked it will still fully slide the panel off the screen. I put a print statement in searchBarCancelButtonClicked to make sure it gets called when the button is pressed and it does. Not sure where else it would be dismissing the entire panel. Thanks in advance for your help and this awesome library!

EDIT: by setting definesPresentationContext to false, pressing Cancel on the searchBar now allows the tableView to go to .half position. However, if the searchBar's textField is active and you attempt to drag the view down manually, the searchBar stays at the top of the screen while the rest of the view slides down.

**Comment by swiftymf** [comment]
![searchBarDetached](https://user-images.githubusercontent.com/13595016/62824180-36571d00-bb4f-11e9-98e7-7a055a8a3e88.gif)

Hope this helps explain what's happening

**Comment by SCENEE** [comment]
Could you tell me the following information?
* iOS version
* The library version
* Xcode version

**Comment by swiftymf** [comment]
simulator iOS version: 12.2
library version: 1.6.3 (just updated, haven't tested it yet)
Xcode: 10.2.1

**Comment by SCENEE** [comment]
Thanks, @swiftymf. I tried to repro this issue on 2 cases with Examples/Maps app, but I'm not able to do that...
1. Add a panel as a child vc
2. Present a panel modally
I wonder if what is the difference between your app and Examples/Maps.

**Comment by swiftymf** [comment]
Could it be because I’m adding the searchBar this way tableView.tableaheaderView = searchViewController.searchBar, instead of in storyboard?

**Comment by SCENEE** [comment]
I've understood this issue after my investigation for a while.

In conclusion, we're not able to use UISearchController with FloatingPanelController by the system design.

This is because UISearchController automatically presents itself modally when a user interacts with the search bar. When it displays, it swaps the superview of the search bar into the view managed by itself from the table view. As a result, FloatingPanelController can't control the search bar when UISearchController is active, as you can see from this screen shot.

<img width="365" alt="Screen Shot 2019-08-14 at 20 07 58" src="https://user-images.githubusercontent.com/899487/63027742-7409cc00-bee8-11e9-8921-b800e2d680a9.png">

I tried to find a workaround, including new APIs on iOS 13, but I was not able to find it.

**Comment by eduguru** [comment]
was there a solution found for this? any workaround. am experiencing the same issue

**Comment by Issalk** [comment]
> was there a solution found for this? any workaround. am experiencing the same issue
