### ISSUE TITLE
Unable to Start Initial Position as Tip

### ISSUE THREAD

**Issue by erdemgc** [SCENEE/FloatingPanel#285]
I have tried starting with .tip position. It always starts with .half position.

It always starts with .half position.

I have tried starting with .tip position.

        fpc = FloatingPanelController()
        let viewController = self.storyboard?.instantiateViewController(withIdentifier: "optionsViewController") as! OptionsViewController
        fpc.set(contentViewController: viewController)
        fpc.track(scrollView: viewController.collectionView)
        fpc.layout.initialPosition = .tip
        fpc.addPanel(toParent: self)

- [ ] CocoaPods
iOS 10.0 >
XCode 11.2

**Comment by SCENEE** [comment]
This is because the layout object will be replaced when `func floatingPanel(_ vc: FloatingPanelController, layoutFor newCollection: UITraitCollection) -> FloatingPanelLayout?`  delegate method is called.

To fix this issue, you need to create a custom layout object and returns the delegate method.

The API design will be resolved in v2.0.

**Comment by nikhil191090** [comment]
Hello, @SCENEE I also need to start the initial position from tip. how can I do it @erdemgc please help, I am kind of stuck here
