### ISSUE TITLE
floatingPanelDidChangePosition is triggered too early - during transition/animation.

### ISSUE THREAD

**Issue by jhickmanEB** [SCENEE/FloatingPanel#365]
### Description

The method `floatingPanelDidChangePosition` is triggered too early and multiple times during a position transition.

### Expected behavior

The method `floatingPanelDidChangePosition` should be triggered once the floating panel has fully moved to it's new position and animations have finished. 

### Actual behavior

The method `floatingPanelDidChangePosition` is triggered while the floating panel is still transitioning to the new position. This is misleading as the method is  `floatingPanelDidChangePosition` and not `floatingPanelIsChangingPosition`

### Steps to reproduce

1. Set a breakpoint in `floatingPanelDidChangePosition` delegate method.

1. Do a quick swipe to hide the floating panel.

1. Observe the breakpoint is triggered while the floating panel is still transitioning and in view.

**Code example that reproduces the issue**

```
    func floatingPanelDidChangePosition(_ vc: FloatingPanelController) {
        // Set a breakpoint in here
    }
```

**How do you display panel(s)?**

* Present modally

**How many panels do you displays?**

* 1 

### Environment

**Library version**

1.7.5

**Installation method**

* Swift Package Manager
 
**iOS version(s)**

13.3

**Xcode version**

11.3.1

**Comment by SCENEE** [comment]
Thank you for asking about it. There are 2 reasons to change the position property at the time.

1. FloatingPanel uses a spring animation to move a new position. According to Core Animation mechanism, the view model properties are necessary to change before starting an animation or the animation block. So the position property is changed before a panel's move.
2. It's actually hard to detect whether a panel is at a new position because moving a panel can be cancelled before it settles at a precise position(the resolution is usually less than 1pt).
