### ISSUE TITLE
Swift file name space

### ISSUE THREAD

**Issue by wendaQueue** [scenee/FloatingPanel#415]
Hello:

This is no a bug. I think you write swift file name space isn't correct. You should add project prefix at your swift file name. Some like this, you should use FloatingPanelController not Controller. The swift file name of  Controller, make me confused. 

Thanks

**Comment by zntfdr** [comment]
Pretty sure you can use `FloatingPanel.Controller` or similar on your side. Or even add type aliases (again, on your side).

No need to change the library API 👍🏻

**Comment by scenee** [comment]
I really worried about that. But I decided to take 'FloatingPanel' prefix away from all filenames(except for the header file for ObjC). It's not familiar with you at first, but I like that because it reduces the width of the navigation panel in Xcode and don't need you to read 13 chars every time to find it.
