### ISSUE TITLE
floatingPanelDidMove and position

### ISSUE THREAD

**Issue by andreaslindahl** [SCENEE/FloatingPanel#46]
In the delegate method `floatingPanelDidMove` the position property of the FloatingPanelController is still the old, previous position. Why is this? After the panel has been moved up or down, I would expect the position property to return the new position (tip, half or full) after the move.

Also, floatingPanelDidMove doesn't seem to be called when the position is changed programmatically?

I'm trying to detect when the panel is moved, by the user or programmatically, and run different code depending on the new position.

**Comment by SCENEE** [comment]
> Why is this? 

`floatingPanelDidMove` is called when a user is dragging the panel. At the time, FloatingPanelController.position property has not been settled yet. Because...
-  A user would let it go to the next position with a flick gesture, or go back to the nearby position.
-  It can't know an expected position is full or half if it's in the middle.

So it's has a previous value. 

I think you can detect an expected condition with `FloatingPanelController.originYOfSurface(for:)` and `FloatingPanelController.surfaceView.frame.minY`

> Also, floatingPanelDidMove doesn't seem to be called when the position is changed programmatically?

I think it's should be! I will change it.

**Comment by andreaslindahl** [comment]
You could keep floatingPanelDidMove the way it is and add another delegate method - floatingPanelDidChangePosition or floatingPanelDidChangeState - that is called everytime FloatingPanelController.position is changed. That way, there's a delegate method that can be used to keep track of all state changes, no matter if they are done programmatically or by the user.

**Comment by SCENEE** [comment]
@andreaslindahl,

Could you have a look at  https://github.com/SCENEE/FloatingPanel/commit/c0647017b5dafb1cfec0fbcb52a490a92dc042c8 ?

I'm thinking about whether the delegate should be called on animation start or finish. In my option, animation start's better because the surface view's frame is same as the settled position in the model layer.

**Comment by andreaslindahl** [comment]
Looks good. That's exactly what I had in mind. Animation start is probably the best solution, yes. That way you could animate something else in sync with the animation of the surface view, if you wish. If the delegate method is called after that animation is done, then it's too late for something like that.

**Comment by SCENEE** [comment]
Thanks for your great insight, @andreaslindahl! I will merge the commit and release it in v1.2.1.

**Comment by andreaslindahl** [comment]
I just tried out the new floatingPanelDidChangePosition delegate method. When accessing theFloatingPanelController.position property in this method, I still get the old state. If I get the state after a small delay I get the new, correct state. I can't figure out why this happens. When the FloatingPanel's state property is set, this delegate method is called. And when I then get the viewcontroller's position property, this just returns the value of the FloatingPanel's state property. So why do I still get the "old" value?

**Comment by SCENEE** [comment]
@andreaslindahl, that's strange 🤔 I can't reproduce your issue at Samples app adding the below code on v1.2.3(latest).
```swift
class SampleListViewController, ... {
    ....
    func floatingPanelDidChangePosition(_ vc: FloatingPanelController) {
        print("#############", mainPanelVC.position)
    }
```
Could you give me a sample to reproduce your issue?

**Comment by andreaslindahl** [comment]
Hm, that's weird. I just do this:

```
func floatingPanelDidChangePosition(_ vc: FloatingPanelController) {
        debugPrint("New position", vc.position)
}
```

Which prints the "old" position. I'll see if I can reproduce it using the samples app.

**Comment by andreaslindahl** [comment]
Nevermind. I did a clean of the build folder and now everything works as it should :)
