### ISSUE TITLE
Dismiss presented view controller programmatically, calling a method of FloatingPanelControllerDelegate

### ISSUE THREAD

**Issue by yspreen** [scenee/FloatingPanel#479]
As far as I can tell, there is no way to programmatically dismiss a presented VC while informing the fpc delegate of its dismissal.

If there is: it's really hard to find this in the documentation. I've been looking for hours.

What I expect would be a call to `vc.dismiss(animated: true, completion: nil)` triggering the presenting fpc's delegate `floatingPanelDidRemove`

I even tried calling `(presentingViewController as? FloatingPanelController)?.delegate?.floatingPanelDidRemove`, as the completion param of `vc.dismiss`, but that doesn't work either.

**Comment by scenee** [comment]
`floatingPanelDidRemove` is called when a panel is removed from the parent view controller as [its doc comment](https://github.com/scenee/FloatingPanel/blob/master/Sources/Controller.swift#L79) mentioned. That means this delegate method isn't called when a panel presents as a modality. This is because  the completion block in `vc.dismiss(animated:completion:)` is the same effect as the delegate method for then modal panel.
