### ISSUE TITLE
SurfaceAppearance class is not compiling with Xcode 14 beta

### ISSUE THREAD

**Issue by mdeaconu** [scenee/FloatingPanel#543]
### Description
Build is failing with `Stored properties cannot be marked potentially unavailable with '@available'` in `SurfaceAppearance` class.

### Environment

**Library version**
- Latest from main branch

**Installation method**
* Swift Package Manager
 
**iOS version(s)**
- iOS 16 beta

**Xcode version**
- Xcode 14 beta with  Swift version 5.7 (swiftlang-5.7.0.113.202 clang-1400.0.16.2)

**Comment by scenee** [comment]
Thank you for this quick report on Xcode 14 beta, @mdeaconu. And also thank you for this PR, @SuperY.
I'm wondering this error is whether a swift compiler's bug or not because Swift 5.6.1 is ok and there is not mentioned in [swift 5.7 changelog](https://github.com/apple/swift/blob/main/CHANGELOG.md). If I confirm it's the spec on swift 5.7, I will merge #544 to the main.

**Comment by SuperY** [comment]
> Thank you for this quick report on Xcode 14 beta, @mdeaconu. And also thank you for this PR, @SuperY. I'm wondering this error is whether a swift compiler's bug or not because Swift 5.6.1 is ok and there is not mentioned in [swift 5.7 changelog](https://github.com/apple/swift/blob/main/CHANGELOG.md). If I confirm it's the spec on swift 5.7, I will merge #544 to the main.

I have modified the implementation to make it look more reasonable. 
No matter what the problem is, we can first merge to solve this problem.

**Comment by scenee** [comment]
@asiliuk resolved this issue without any API change 🎉  
I really appreciate all of quick contributions for this issue.
