### ISSUE TITLE
Enhancement request: configurability of grabber handle

### ISSUE THREAD

**Issue by natan** [SCENEE/FloatingPanel#70]
Currently, it appears you cannot change the style or position of the grabber handle. I'm building an app that calls for a different width, height, corner radius, and background color compared to the default style. It would be great to allow this to be configurable.

**Comment by natan** [comment]
@SCENEE I'm happy to implement this. Let me know which approach you would prefer:

1. New public properties on `FloatingPanelSurfaceView` that allow configuration of the grabber style.
2. A new `FloatingPanelGrabberStyle` protocol (similar to `FloatingPanelLayoutAdapter`) that you can implement to control these parameters.
3. Something else?

**Comment by SCENEE** [comment]
Hello, @natan! 
The current implementation takes no.3 approach 😃  
A user can hide the default one and add a custom grabber handle at an appropriate position.

```
fpc.surfaceView.grabberHandle.isHidden = true
fpc.surfaceView.addSubview(myGrabberHandleView)
```

This is because a grabber UI design depends on a design concept and I don't think it's possible to respond all requirements by a designer with a custom properties of the library.

**Comment by natan** [comment]
@SCENEE Ah, I didn't consider that! Would be nice to document this in the README or in the header, I think.

**Comment by SCENEE** [comment]
> Would be nice to document this in the README

Done! https://github.com/SCENEE/FloatingPanel#use-a-custom-grabber-handle
I'll also add a comment about it in the header later. Thanks, @natan!
