### ISSUE TITLE
Adding gesture recognizer to backdropView does not work

### ISSUE THREAD

**Issue by fmessina** [scenee/FloatingPanel#99]
Hi and thanks for the library :)

I've been trying to add a gesture recognizer to the `backdropView` to dismiss the panel, but I can't get it to work. It's like if the selector attached to the gesture never gets called.

I'm on the last version.

This is how I do it (as described here https://github.com/SCENEE/FloatingPanel#add-tap-gestures-to-the-surface-or-backdrop-views)

```swift
let backdropTapGesture = UITapGestureRecognizer(target: self, action: #selector(self.handleBackdropTapGesture(_:)))
self.floatingPanelController.backdropView.addGestureRecognizer(backdropTapGesture)
```
and
```swift
@objc private func handleBackdropTapGesture(_ gesture: UITapGestureRecognizer) {
     // Never gets called
     print("DISMISS")
}
```

If I add the tapGesture on the `surfaceView` everything works.
Any idea?   
Thanks!

**Comment by SCENEE** [comment]
Hello, @fmessina! Thanks for your usage!

I'm sorry I can't reproduce this issue. On Samples app, a tap gesture recognizer added into `backdropView` is working well. https://github.com/SCENEE/FloatingPanel/blob/master/Examples/Samples/Sources/ViewController.swift#L150

But If a `backdropView`'s alpha is zero,  a tap gesture recognizer of it doesn't work by design.

**Comment by fmessina** [comment]
Hi!
Thanks for the quick answer.

Probably then it is because the backdropView's alpha is zero. 

What I’m trying to achieve is a simple “tap outside to dismiss”, no matter if the alpha is zero or not.
I think it is an useful functionality for the library too.

What do you suggest to achieve it?

**Comment by fmessina** [comment]
I ended up with this solution:  
  
In my `FloatingPanelLayout` delegate: 
```swift
    func backdropAlphaFor(position: FloatingPanelPosition) -> CGFloat {
        return position == .half ? 0.05 : 0.0
    }
```

This way I have an almost invisible alpha on the `backdropView` and the dismiss on touch (the one provided by the library) works well.  

Looks a bit like an hack but it works :)

**Comment by SCENEE** [comment]
Let me confirm your background. Do you present a floating panel view controller modally?

**Comment by SCENEE** [comment]
I'm sorry I found an unexpected behavior if a floating panel controller is  presented modally. 

The controller should not block any touch events if the backdrop view's alpha is zero because it seems to able to touch views behind the backdrop view.  I made a `fix-touch-handling-on-presentation-modally` branch on which I fixed it to pass through touch events to the views managed by the presenting view controller.

My original expectation is different from yours. What do you think of the expectation?

**Comment by fmessina** [comment]
I think your expectation is correct too.  

What I wanted is to tap outside to dismiss it, so maybe if the alpha is zero the tap gesture should go on the presenting view controller.  

Thanks for the fix, I will pull it when it will be released.
